import { Link } from 'react-router-dom';
import { CATEGORIES } from '../utils/tracks';
import { APP_NAME, PRICE, PAYMENTS_ENABLED, PRELAUNCH_NOTE } from '../utils/config';
import { useDocumentHead } from '../hooks/useDocumentHead';
import Artwork from '../components/Artwork';
import Logo from '../components/Logo';
import PlayCounter from '../components/PlayCounter';
import EmailCapture from '../components/EmailCapture';

// The landing page. It has three seconds to earn respect. Warm, sparse, and
// confident — let the artwork and the space do the work.
export default function Home() {
  useDocumentHead('/');
  return (
    <main className="page-enter">
      <Hero />
      <Previews />
      <MadeByHand />
      <Proof />
      <Pricing />
      <Footer />
    </main>
  );
}

function Hero() {
  return (
    <section className="mx-auto flex min-h-[76vh] max-w-content flex-col items-center justify-center px-6 text-center">
      <Logo size={52} className="mb-7" />
      <h1 className="text-display text-accent">{APP_NAME}</h1>
      <p className="mt-6 text-xl font-light text-ink-soft">Find your cadence</p>
      <p className="mt-3 max-w-sm text-sm text-ink-faint">
        Acoustic piano, played and recorded by hand. Never generated by AI
      </p>
      <Link to="/app" className="btn-primary mt-12">
        Begin listening
      </Link>
      <p className="text-caption mt-5">No account needed to start</p>
    </section>
  );
}

function Previews() {
  // Every category, artwork forward. Let the work speak; no feature lists.
  // Driven straight off CATEGORIES so it can't drift out of sync with the library.
  return (
    <section className="mx-auto max-w-content px-6 py-20">
      <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
        {CATEGORIES.map((c) => (
          <Link key={c.id} to="/app" className="group block">
            <Artwork
              seed={`${c.id}-preview`}
              style={c.style}
              size={520}
              animate={false}
              className="w-full border border-line transition-transform duration-500 ease-calm group-hover:-translate-y-0.5"
            />
            <h2 className="mt-5 font-display text-2xl text-ink">{c.name}</h2>
            <p className="mt-1 text-sm text-ink-soft">{c.tagline}</p>
          </Link>
        ))}
      </div>
    </section>
  );
}

// The one place the making is stated outright. Positive first — a real
// instrument, a real player — with the absence of generated music as the quiet
// consequence, not the banner. Confidence, not a manifesto.
function MadeByHand() {
  return (
    <section className="mx-auto max-w-content px-6 pb-16">
      <div className="panel mx-auto max-w-2xl p-9 text-center">
        <p className="text-label text-ink-soft">How it's made</p>
        <h2 className="text-h2 mt-3 text-ink">Someone sat down and played this</h2>
        <p className="mx-auto mt-5 max-w-lg text-sm leading-relaxed text-ink-soft">
          Every piece here is an acoustic piano performance — played, recorded and mastered by
          hand, one at a time. <span className="text-ink">No AI is used anywhere in this
          catalogue</span>: nothing is generated, and nothing is assembled from a model. It is
          simply the music we wanted to work to, made carefully enough to disappear into.
        </p>
      </div>
    </section>
  );
}

function Proof() {
  // A single quiet line. Renders nothing until the number is real and large
  // enough to persuade.
  return (
    <section className="mx-auto max-w-content px-6 pb-4 text-center">
      <PlayCounter />
    </section>
  );
}

function Pricing() {
  return (
    <section className="mx-auto max-w-content px-6 py-20">
      <div className="panel mx-auto max-w-md p-9 text-center">
        <h2 className="text-h2 text-ink">The full collection</h2>
        <div className="mt-6 flex items-baseline justify-center gap-2">
          <span className="font-display text-5xl font-light text-ink">${PRICE.amount}</span>
          <span className="text-ink-soft">/ month</span>
        </div>
        <p className="mx-auto mt-5 max-w-xs text-sm leading-relaxed text-ink-soft">
          Every piece in the library, and every new one as it's recorded. Renews monthly at $
          {PRICE.amount}; cancel anytime.
        </p>
        {PAYMENTS_ENABLED ? (
          <Link to="/app?subscribe=1" className="btn-primary mt-8 w-full">
            Subscribe — {PRICE.label}
          </Link>
        ) : (
          <p className="mt-8 rounded-lg border border-line bg-paper-wash px-4 py-3 text-sm text-ink-soft">
            {PRELAUNCH_NOTE}
          </p>
        )}
        <p className="text-caption mt-4">
          Free to begin, with no account. The free pieces play for as long as you like — no clock,
          no daily limit, and nothing that stops the music. Plays on with your screen off.
        </p>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-line">
      <div className="mx-auto flex max-w-content flex-col items-center gap-6 px-6 py-12 text-center">
        <Link to="/" className="flex items-center gap-2.5">
          <Logo size={24} />
          <span className="font-display text-2xl text-accent">{APP_NAME}</span>
        </Link>
        <div className="flex gap-7">
          {[
            ['/science', 'Science'],
            ['/privacy', 'Privacy'],
            ['/terms', 'Terms'],
            ['/account', 'Account'],
          ].map(([to, label]) => (
            <Link key={to} to={to} className="text-label text-ink-soft hover:text-ink">
              {label}
            </Link>
          ))}
        </div>
        <EmailCapture compact />
        <p className="text-caption">© {new Date().getFullYear()} {APP_NAME}. No ads. No data sold.</p>
      </div>
    </footer>
  );
}
