import { useDocumentHead } from '../hooks/useDocumentHead';

// The science, stated plainly.
//
// The rule for this page: every claim is either supported by a linked study or
// is openly labelled as a design choice rather than a finding. Where the
// evidence is mixed we say so, and where the industry overclaims we say that
// too. It is a better sales page for being honest, and it is the only version
// compatible with the rest of the product's voice.

const DEBUNKED = [
  {
    claim: 'Binaural beats tune your brainwaves',
    reality:
      'The evidence is genuinely inconsistent. A meta-analysis found a medium pooled effect, but the same literature reports conflicting results across attention and memory, and a large parametric study found no reliable improvement in sustained attention. One study set out to measure the effect on EEG power and emotional arousal and failed to find it. Nothing here uses binaural beats.',
  },
  {
    claim: 'A specific frequency unlocks focus',
    reality:
      'There is no frequency that reliably produces concentration, and no serious literature supporting one. Claims of a magic Hz number are marketing, not findings.',
  },
  {
    claim: 'Focus music works for everyone',
    reality:
      'It does not. The effect depends on the person, the task and the music — background music measurably harms some people on some work. This is the single most over-promised part of the category, and the reason the research looks more impressive in advertising than it does in journals.',
  },
];

const PRINCIPLES = [
  {
    title: 'No words',
    body: 'Every piece is instrumental. Speech gets automatic, obligatory access to the same phonological working memory you use to read and write, and disrupts it — even when the speech is meaningless, unfamiliar, or in a language you do not speak. Lyrics are the best-evidenced way to make background music worse for verbal work.',
  },
  {
    title: 'Nothing sudden',
    body: 'Attention orients to abrupt sound automatically — you do not get to decide. So these pieces move slowly and evenly: no sforzando, no sudden register jumps, no dramatic swells. Every jolt is a listener pulled out of their work.',
  },
  {
    title: 'A steady floor',
    body: 'Intelligible speech is the most disruptive thing in a shared room, and its cost rises with how intelligible it is. Continuous, even sound raises the floor so a passing conversation stops resolving into words. This is the same principle as office sound masking, which is well studied — it is also why silence is not always the best condition.',
  },
  {
    title: 'Predictable, not novel',
    body: 'Familiar music demands less of you than unfamiliar music. In a 2025 study, listeners were more likely to mind-wander with unfamiliar music than with familiar music, and responded about 170 ms faster on a semantic task with familiar music. The proposed mechanism is not sentiment or association — familiar music generates stronger expectancies, so it draws on fewer cognitive resources. Music you have heard before gets out of the way more easily.',
  },
  {
    title: 'The right level',
    body: 'Deep Focus, Creativity and Calm sit at different levels of arousal, so you can match the sound to the work. Arousal genuinely interacts with performance, and it interacts differently for different people — which is why we offer a range rather than one prescribed setting.',
  },
  {
    title: 'No AI, anywhere',
    body: 'Every piece is an acoustic piano performance, recorded and mastered by hand. None of it is generated by AI. That is a choice about craft and ownership rather than a claim about your attention — we are not going to pretend a study says real pianos help you concentrate more than synthesised ones.',
  },
];

const RESEARCH = [
  {
    heading: 'On binaural beats and entrainment',
    items: [
      {
        label:
          'Potential of binaural beats intervention for improving memory and attention: meta-analysis and systematic review',
        note: 'Psychological Research, 2022 — a medium pooled effect, alongside conflicting results across studies.',
        href: 'https://link.springer.com/article/10.1007/s00426-022-01706-7',
      },
      {
        label: 'A parametric investigation of binaural beats for brain entrainment and sustained attention',
        note: 'Scientific Reports, 2025 — a large study finding no reliable gain in sustained attention.',
        href: 'https://www.nature.com/articles/s41598-025-88517-z',
      },
      {
        label: 'Binaural beat: a failure to enhance EEG power and emotional arousal',
        note: 'A direct attempt to measure the claimed mechanism, which did not find it.',
        href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5694826/',
      },
    ],
  },
  {
    heading: 'On why lyrics and speech disrupt',
    items: [
      {
        label: 'The importance of semantic similarity to the irrelevant speech effect',
        note: 'Memory & Cognition — irrelevant speech disrupts serial recall even when you are ignoring it.',
        href: 'https://link.springer.com/article/10.3758/BF03201211',
      },
      {
        label:
          'Impact of irrelevant speech and non-speech sounds on serial recall of verbal and spatial items',
        note: 'Scientific Reports, 2025 — speech impairs verbal recall specifically, in children and adults.',
        href: 'https://www.nature.com/articles/s41598-025-85855-w',
      },
    ],
  },
  {
    heading: 'On masking and the acoustic floor',
    items: [
      {
        label:
          'Effects of speech intelligibility and work modality on reading productivity in open-plan offices',
        note: 'Building and Environment — reading productivity tracks how intelligible surrounding speech is.',
        href: 'https://www.sciencedirect.com/science/article/abs/pii/S0360132323007618',
      },
      {
        label: 'Level-adaptive sound masking in the open-plan office',
        note: 'Applied Acoustics — masking, noise distraction and coping, measured in the field.',
        href: 'https://www.sciencedirect.com/science/article/pii/S0003682X23006436',
      },
    ],
  },
  {
    heading: 'On familiarity, mind-wandering and individual differences',
    items: [
      {
        label: 'Familiar music reduces mind wandering and boosts behavioural performance',
        note: 'Brain Sciences, 2025 (n = 96) — the familiarity finding, and its attentional-resources explanation.',
        href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12109699/',
      },
      {
        label:
          'Music is as distracting as noise: differential distraction of background music on introverts and extraverts',
        note: 'Ergonomics — introverts are more impaired by background music on complex tasks.',
        href: 'https://pubmed.ncbi.nlm.nih.gov/11964204/',
      },
      {
        label: 'The effect of background music and background noise on the task performance of introverts and extraverts',
        note: 'Psychology of Music, 2007 — high-arousal music was worse than low-arousal music and silence.',
        href: 'https://journals.sagepub.com/doi/10.1177/0305735607076444',
      },
      {
        label: 'Music as a contextual cue in human predictive learning',
        note: 'Learning and Motivation, 2025 — on music as a context cue, an effect that is real but mixed.',
        href: 'https://www.sciencedirect.com/science/article/pii/S0023969025000037',
      },
    ],
  },
];

export default function Science() {
  useDocumentHead('/science');
  return (
    <main className="page-enter mx-auto max-w-3xl px-6 py-20">
      <h1 className="text-h1 text-ink">The science, plainly</h1>

      <p className="mt-8 text-lg font-light leading-relaxed text-ink-soft">
        There is no magic frequency, and we do not claim one. The aim is quieter and more honest:
        music <span className="text-ink">played to stay out of your way</span>. No words, nothing
        sudden, a steady acoustic floor that masks distraction — so the loudest thing in the room is
        the work.
      </p>

      <p className="mt-5 leading-relaxed text-ink-soft">
        This page is here because most focus-audio marketing overstates what is known. Below is what
        we do not claim, what we think genuinely helps and why, and links to the research so you can
        disagree with us.
      </p>

      <h2 className="text-h2 mt-16 text-ink">What we do not claim</h2>
      <div className="mt-5 space-y-4">
        {DEBUNKED.map((d) => (
          <div key={d.claim} className="panel p-6">
            <p className="font-display text-lg text-ink">
              <span className="text-ink-faint">✕</span> {d.claim}
            </p>
            <p className="mt-2 text-sm leading-relaxed text-ink-soft">{d.reality}</p>
          </div>
        ))}
      </div>

      <h2 className="text-h2 mt-16 text-ink">What we think helps, and why</h2>
      <div className="panel mt-5 overflow-hidden">
        <table className="w-full text-left text-sm">
          <thead className="text-label text-ink-soft">
            <tr>
              <th className="px-5 py-4 font-medium">Principle</th>
              <th className="px-5 py-4 font-medium">Why it helps</th>
            </tr>
          </thead>
          <tbody>
            {PRINCIPLES.map((p) => (
              <tr key={p.title} className="border-t border-line align-top">
                <td className="px-5 py-4 text-ink sm:whitespace-nowrap">{p.title}</td>
                <td className="px-5 py-4 leading-relaxed text-ink-soft">{p.body}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="text-h2 mt-16 text-ink">Why it may not work for you</h2>
      <p className="mt-5 leading-relaxed text-ink-soft">
        Background music is not uniformly good for concentration, and we would rather say so. It
        tends to help least — and can actively hurt — when the work is verbally demanding, when the
        music is high-arousal, and for people who are more sensitive to distraction in the first
        place. Introverts, in particular, are more impaired by background sound on complex tasks
        than extraverts are.
      </p>
      <p className="mt-4 leading-relaxed text-ink-soft">
        That variability is the honest explanation for why this category promises more than it can
        prove: pooled results hide the fact that the same track helps one person and disrupts
        another. The only reliable test is your own. If you concentrate better in silence, do that —
        we would rather you knew than kept paying for something that is not working.
      </p>

      <h2 className="text-h2 mt-16 text-ink">The research</h2>
      <p className="mt-4 text-sm text-ink-soft">
        Primary sources, including the ones that undercut the category. Some are paywalled; the
        abstracts carry the finding.
      </p>
      <div className="mt-6 space-y-8">
        {RESEARCH.map((group) => (
          <div key={group.heading}>
            <h3 className="text-label text-ink-soft">{group.heading}</h3>
            <ul className="mt-3 space-y-4">
              {group.items.map((s) => (
                <li key={s.href}>
                  <a
                    href={s.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-accent underline-offset-4 transition-colors hover:text-ink hover:underline"
                  >
                    {s.label}
                  </a>
                  <p className="text-caption mt-1">{s.note}</p>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div className="panel mt-16 p-7">
        <h3 className="font-display text-xl text-ink">An honest note</h3>
        <p className="mt-3 text-sm leading-relaxed text-ink-soft">
          Music helps many people concentrate — but not everyone, and not for every task. The
          research is genuinely mixed, and the effect depends on the person and the work. We design
          against the things that are well evidenced to disrupt attention, which is a more modest
          claim than the one usually made, and one we can stand behind. This is music, not medicine.
          It is no substitute for professional care for sleep or anxiety.
        </p>
      </div>
    </main>
  );
}
