// Single source of truth for per-route title/description, keyed by path.
// Consumed by both the frontend (useDocumentHead, for the client-rendered
// page and JS-executing crawlers like Googlebot) and the Worker
// (HTMLRewriter, for the raw HTML that non-JS crawlers and social-media
// unfurlers see) — keeping the two from silently drifting apart. Plain data,
// no DOM/browser APIs, so it's safe to import from both bundles.
export const PAGE_META = {
  '/': {
    title: 'Cadenzia — Find your cadence',
    description:
      'Acoustic piano for deep focus, creativity, and calm — played and recorded by hand, never generated by AI.',
  },
  '/app': {
    title: 'Listen — Cadenzia',
    description:
      'Stream acoustic piano for deep focus, creativity, and calm — never generated by AI. Free to begin, with no time limit.',
  },
  '/science': {
    title: 'The science, plainly — Cadenzia',
    description:
      'What focus music can and cannot do — no binaural beats, no magic frequency — and the research behind how Cadenzia is made.',
  },
  '/privacy': {
    title: 'Privacy — Cadenzia',
    description: 'What Cadenzia stores, what it never does, and how to delete your data.',
  },
  '/terms': {
    title: 'Terms — Cadenzia',
    description: 'The complete terms of service for Cadenzia, in plain English.',
  },
  '/account': {
    title: 'Account — Cadenzia',
    description: 'Sign in, manage your subscription, and control your data.',
  },
};
